const fs = require('fs');
const path = require('path');
const dirs = ['src/domain/entities','src/domain/repositories','src/application/use-cases','src/infrastructure/database','src/infrastructure/http/controllers','src/infrastructure/http/routes','prisma'];
dirs.forEach(d => fs.mkdirSync(d, { recursive: true }));
const files = {
  'prisma/schema.prisma': generator client { provider = "prisma-client-js" }\ndatasource db { provider = "sqlite"\n url = "file:./dev.db" }\nmodel Team { id Int @id @default(autoincrement())\n name String @unique\n score Int @default(0)\n solved Int @default(0)\n completed String @default("[]")\n createdAt DateTime @default(now()) },
  'src/domain/entities/Team.ts': export class Team { constructor(public readonly id: number, public readonly name: string, public score: number, public solved: number, public completed: string[]) {} },
  'src/domain/repositories/ITeamRepository.ts': import { Team } from '../entities/Team';\nexport interface ITeamRepository { findByName(name: string): Promise<Team | null>; save(team: Team): Promise<Team>; getTopTeams(): Promise<Team[]>; },
  'src/infrastructure/database/PrismaTeamRepository.ts': import { PrismaClient } from '@prisma/client';\nimport { ITeamRepository } from '../../domain/repositories/ITeamRepository';\nimport { Team } from '../../domain/entities/Team';\nconst prisma = new PrismaClient();\nexport class PrismaTeamRepository implements ITeamRepository { async findByName(name: string): Promise<Team | null> { const data = await prisma.team.findUnique({ where: { name } }); if (!data) return null; return new Team(data.id, data.name, data.score, data.solved, JSON.parse(data.completed)); }\n async save(team: Team): Promise<Team> { const data = await prisma.team.upsert({ where: { name: team.name }, update: { score: team.score, solved: team.solved, completed: JSON.stringify(team.completed) }, create: { name: team.name, score: team.score, solved: team.solved, completed: JSON.stringify(team.completed) } }); return new Team(data.id, data.name, data.score, data.solved, JSON.parse(data.completed)); }\n async getTopTeams(): Promise<Team[]> { const data = await prisma.team.findMany({ orderBy: { score: 'desc' } }); return data.map(d => new Team(d.id, d.name, d.score, d.solved, JSON.parse(d.completed))); } },
  'src/application/use-cases/SubmitFlag.ts': import { ITeamRepository } from '../../domain/repositories/ITeamRepository';\nconst missions = [{ id: '01', title: 'INFILTRACI"N', phase: 'ACCESO INICIAL', points: 100, flag: 'ONEFLAG{ECHO_INIT}' },{ id: '02', title: 'RUTEO', phase: 'ESCALADA DE PRIVILEGIOS', points: 150, flag: 'ONEFLAG{ROUTE_BYPASS}' },{ id: '03', title: 'FANTASMA', phase: 'EVASI"N DE DEFENSA', points: 200, flag: 'ONEFLAG{GHOST_PROTOCOL}' },{ id: '04', title: 'NEXUS', phase: 'MOVIMIENTO LATERAL', points: 250, flag: 'ONEFLAG{NEXUS_ACCESS}' },{ id: '05', title: 'PANTHEON', phase: 'DECISI"N // ASCENSI"N FINAL', points: 300, flag: 'ONEFLAG{PANTHEON_FREE}' }];\nexport class SubmitFlag { constructor(private teamRepo: ITeamRepository) {}\n async execute(teamName: string, flag: string) { if (!teamName || !flag) throw new Error("Datos invalidos"); let team = await this.teamRepo.findByName(teamName); const mission = missions.find(m => m.flag === flag.trim().toUpperCase()); if (!mission) throw new Error("FLAG REJECTED // SIGNATURE DOES NOT MATCH"); if (!team) { team = await this.teamRepo.save({ id: 0, name: teamName, score: 0, solved: 0, completed: [] } as any); } if (team.completed.includes(mission.id)) { throw new Error("Mision ya completada por este equipo"); } team.completed.push(mission.id); team.score += mission.points; team.solved += 1; await this.teamRepo.save(team); return { id: mission.id, title: mission.title }; } },
  'src/application/use-cases/GetScoreboard.ts': import { ITeamRepository } from '../../domain/repositories/ITeamRepository';\nexport class GetScoreboard { constructor(private teamRepo: ITeamRepository) {}\n async execute() { return await this.teamRepo.getTopTeams(); } },
  'src/infrastructure/http/controllers/TeamController.ts': import { Request, Response } from 'express';\nimport { SubmitFlag } from '../../../application/use-cases/SubmitFlag';\nimport { GetScoreboard } from '../../../application/use-cases/GetScoreboard';\nimport { PrismaTeamRepository } from '../../database/PrismaTeamRepository';\nconst repo = new PrismaTeamRepository();\nconst submitFlag = new SubmitFlag(repo);\nconst getScoreboard = new GetScoreboard(repo);\nexport class TeamController { static async submit(req: Request, res: Response): Promise<void> { try { const { team, flag } = req.body; const result = await submitFlag.execute(team, flag); res.json({ message: \FLAG ACCEPTED // \ \\ }); } catch (e: any) { res.status(400).json({ error: e.message }); } }\n static async scoreboard(req: Request, res: Response): Promise<void> { try { const teams = await getScoreboard.execute(); res.json(teams); } catch (e: any) { res.status(500).json({ error: \"Error interno" }); } } },
  'src/infrastructure/http/routes/index.ts': import { Router } from 'express';\nimport { TeamController } from '../controllers/TeamController';\nconst router = Router();\nrouter.post('/submit', TeamController.submit);\nrouter.get('/scoreboard', TeamController.scoreboard);\nexport default router;,
  'src/index.ts': import express from 'express';\nimport cors from 'cors';\nimport routes from './infrastructure/http/routes';\nconst app = express();\napp.use(cors());\napp.use(express.json());\napp.use('/api', routes);\nconst port = process.env.PORT || 4000;\napp.listen(port, () => { console.log(\Backend corriendo en puerto \\); });
};
for (const [file, content] of Object.entries(files)) { fs.writeFileSync(file, content.trim()); }
console.log('Archivos generados.');
